# Generated by Django 3.1.7 on 2021-03-18 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockreceipts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransactions',
            fields=[
                ('id', models.CharField(db_column='ID', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('StockTransactiontype', models.IntegerField(db_column='StockTransactionTYPE')),
                ('status', models.IntegerField(db_column='STATUS')),
                ('datenew', models.DateTimeField(db_column='DATENEW')),
                ('person', models.ForeignKey(db_column='PERSON', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'StockTransactionS',
                'db_table': 'StockTransactionS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockTransactionlines',
            fields=[
                ('id', models.AutoField(db_column='ID', editable=False, primary_key=True, serialize=False)),
                ('line', models.IntegerField(blank=True, db_column='LINE', null=True)),
                ('units', models.FloatField(db_column='UNITS')),
                ('LinePrice', models.FloatField(db_column='LINEPRICE')),
                ('StockTransaction', models.ForeignKey(db_column='StockTransaction', on_delete=django.db.models.deletion.DO_NOTHING, to='stocktransactions.stocktransactions')),
                ('product', models.ForeignKey(blank=True, db_column='PRODUCT', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stockreceipts.products')),
            ],
            options={
                'db_table': 'StockTransactionLINES',
                'managed': True,
                'unique_together': {('StockTransaction', 'line')},
            },
        ),
    ]
