# Generated by Django 3.1.7 on 2021-03-22 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stockreceipts', '__first__'),
        ('stocktransactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='datenew',
            field=models.DateTimeField(db_column='DATENEW', default=datetime.datetime(2021, 3, 22, 18, 14, 26, 140845)),
        ),
      
    ]
