# Generated by Django 3.1.7 on 2021-03-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktransactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stocktransactions',
            table='StockTransactions',
        ),
    ]
