# Generated by Django 3.1.7 on 2021-03-20 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocktransactions', '0002_auto_20210318_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransactions',
            options={'managed': True, 'verbose_name_plural': 'StockTransactions'},
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='StockTransactiontype',
            field=models.IntegerField(choices=[(0, 'sales'), (1, 'purchases'), (2, 'sales return'), (3, 'purchases returns'), (4, 'sales return'), (5, 'purchases returns')], db_column='StockTransactionTYPE', default=0),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='datenew',
            field=models.DateTimeField(db_column='DATENEW', default=datetime.datetime(2021, 3, 20, 15, 37, 45, 258941)),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='person',
            field=models.ForeignKey(db_column='PERSON', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='status',
            field=models.IntegerField(db_column='STATUS', default=0),
        ),
    ]
