# Generated by Django 3.1.7 on 2021-03-20 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktransactions', '0003_auto_20210320_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='StockTransactiontype',
            field=models.IntegerField(choices=[(0, 'sales'), (1, 'purchases'), (2, 'sales return'), (3, 'purchases returns'), (4, 'sales return'), (5, 'purchases returns')], db_column='STOCKTRANSACTIONTYPE', default=0),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='datenew',
            field=models.DateTimeField(db_column='DATENEW', default=datetime.datetime(2021, 3, 20, 15, 41, 23, 689401)),
        ),
    ]
