# Generated by Django 3.1.7 on 2021-03-22 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktransactions', '0004_auto_20210322_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='datenew',
            field=models.DateTimeField(db_column='DATENEW', default=datetime.datetime(2021, 3, 22, 18, 37, 14, 804559)),
        ),
    ]
