# Generated by Django 3.1.7 on 2021-03-20 17:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocktransactions', '0004_auto_20210320_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='StockTransactiontype',
            field=models.IntegerField(choices=[(0, 'Sales'), (1, 'Purchases'), (2, 'sales return'), (3, 'purchases returns')], db_column='STOCKTRANSACTIONTYPE', default=1),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='datenew',
            field=models.DateTimeField(db_column='DATENEW', default=datetime.datetime(2021, 3, 20, 19, 28, 31, 930131)),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='person',
            field=models.ForeignKey(db_column='PERSON', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='stocktransactionlines',
            unique_together={('StockTransaction', 'id')},
        ),
        migrations.RemoveField(
            model_name='stocktransactionlines',
            name='line',
        ),
    ]
