# Generated by Django 3.1.7 on 2021-03-21 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockreceipts', '__first__'),
        ('stocktransactions', '0005_auto_20210320_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransactionlines',
            name='stockdiary',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockreceipts.stockdiary'),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='datenew',
            field=models.DateTimeField(db_column='DATENEW', default=datetime.datetime(2021, 3, 21, 11, 47, 22, 255411)),
        ),
        migrations.AlterModelTable(
            name='stocktransactionlines',
            table='StockTransactionLines',
        ),
    ]
