# Generated by Django 3.1.7 on 2021-03-22 18:23

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stocktransactions', '0006_auto_20210322_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransactionlines',
            name='stockdiary',
        ),
        migrations.AlterField(
            model_name='stocktransactionlines',
            name='id',
            field=models.CharField(db_column='ID', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='datenew',
            field=models.DateTimeField(db_column='DATENEW', default=datetime.datetime(2021, 3, 22, 20, 23, 18, 463093)),
        ),
    ]
