# Generated by Django 3.1.7 on 2021-03-21 12:31

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stocktransactions', '0008_auto_20210321_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactionlines',
            name='id',
            field=models.CharField(db_column='ID', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='datenew',
            field=models.DateTimeField(db_column='DATENEW', default=datetime.datetime(2021, 3, 21, 14, 31, 52, 680918)),
        ),
    ]
