# Generated by Django 3.1.7 on 2021-03-21 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockreceipts', '__first__'),
        ('stocktransactions', '0009_auto_20210321_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactionlines',
            name='id',
            field=models.AutoField(db_column='ID', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stocktransactionlines',
            name='stockdiary',
            field=models.OneToOneField(db_column='stockdiary', null=True, on_delete=django.db.models.deletion.CASCADE, to='stockreceipts.stockdiary'),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='datenew',
            field=models.DateTimeField(db_column='DATENEW', default=datetime.datetime(2021, 3, 21, 14, 39, 33, 704108)),
        ),
    ]
