# Generated by Django 3.1.7 on 2021-03-21 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stockreceipts', '__first__'),
        ('stocktransactions', '0010_auto_20210321_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransactionlines',
            name='ID',
            field=models.OneToOneField(db_column='ID', default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stockreceipts.stockdiary'),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='datenew',
            field=models.DateTimeField(db_column='DATENEW', default=datetime.datetime(2021, 3, 21, 14, 47, 8, 973406)),
        ),
        migrations.AlterUniqueTogether(
            name='stocktransactionlines',
            unique_together={('StockTransaction', 'ID')},
        ),
        migrations.RemoveField(
            model_name='stocktransactionlines',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stocktransactionlines',
            name='stockdiary',
        ),
    ]
