# Generated by Django 3.1.7 on 2021-03-21 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockreceipts', '__first__'),
        ('stocktransactions', '0012_auto_20210321_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactionlines',
            name='stockdiary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockreceipts.Stockdiary'),
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='datenew',
            field=models.DateTimeField(db_column='DATENEW', default=datetime.datetime(2021, 3, 21, 16, 7, 21, 795210)),
        ),
    ]
